ALTER TABLE `project-c9256c63-847c-4b18-ac8.gastos.expenses`
ADD COLUMN IF NOT EXISTS trip_id STRING,
ADD COLUMN IF NOT EXISTS original_amount NUMERIC,
ADD COLUMN IF NOT EXISTS original_currency STRING,
ADD COLUMN IF NOT EXISTS fx_rate NUMERIC,
ADD COLUMN IF NOT EXISTS fx_provider STRING,
ADD COLUMN IF NOT EXISTS fx_date DATE,
ADD COLUMN IF NOT EXISTS amount_mxn_source STRING;
